export function successResponse(data, status = 200) {
  return Response.json({ success: true, data }, { status });
}

export function errorResponse(message, code, status = 400, extra = {}) {
  return Response.json({ success: false, error: message, code, ...extra }, { status });
}

// Standard error codes
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  COUPON_INVALID: 'COUPON_INVALID',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INVALID_ID: 'INVALID_ID',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  FORBIDDEN_ACCESS: 'FORBIDDEN_ACCESS',
  ADDRESS_LIMIT_EXCEEDED: 'ADDRESS_LIMIT_EXCEEDED',
  OUT_OF_SERVICE_AREA: 'OUT_OF_SERVICE_AREA',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  COUPON_CONDITIONS_NOT_MET: 'COUPON_CONDITIONS_NOT_MET',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_STATE: 'INVALID_STATE',
  CANCELLATION_NOT_ALLOWED: 'CANCELLATION_NOT_ALLOWED',
};
